[env]
_.python.venv = { path = ".venv", create = true }

[tools]
node = "22"
pnpm = "latest"
python = "3.13"
uv = "latest"

[tasks.install]
description = "Install packages"
run = [
    "pnpm install",
    "uv sync"
]
