FROM nginx:stable
# FROM nginx:1.28-bookworm
# FROM nginx:1.28-bookworm-perl
# FROM nginx:1.28-bookworm-otel
# perl: Perl
# otel: OpenTelemetory

COPY ./_sites/yp /usr/share/nginx/yp
COPY ./_sites/yp-beta /usr/share/nginx/yp-beta
COPY ./share/007144-nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 7143
